---
# This Taskfile defines a set of tasks that can be run using the `task` command.
# To invoke a task, use the command `task <task_name>`. For example, to run the `init` task, use `task init`.

# This is the version of the Taskfile format being used
version: "3"
# Define the tasks that can be run
tasks:
  generate:
    desc: "Generate the codebase"
    dir: "{{.TASKFILE_DIR}}"
    aliases: ["g"] # Short alias for the format task
    cmds:
      - uv run terraform-provider-lago
      - tfplugingen-openapi generate lago_openapi.yaml
      - tfplugingen-framework generate provider --package provider --input provider_code_spec.json -output internal/provider
      - tfplugingen-framework generate resources --input provider_code_spec.json -output internal/provider
      # - tfplugingen-framework generate data-sources --input provider_code_spec.json -output internal/data_sources
      # - tfplugingen-framework scaffold provider --name lago --output-dir internal/provider
      - go generate

  download_spec:
    desc: "Download the Lago OpenAPI spec"
    cmds:
      - curl -o lago_openapi.yaml https://swagger.getlago.com/openapi.yaml
