// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package lago

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func LagoProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type LagoModel struct {
}
